// Converts data/course.kml (the WTM course KMZ, unzipped) into
// assets/course-data.js — one lap as lat/lng points plus obstacle
// locations. Re-run after replacing the KML:
//   node scripts/build-course.mjs

import { readFileSync, writeFileSync } from "node:fs";

// Display names for obstacles 1–20, from the WTM live obstacle list.
const OBSTACLE_NAMES = [
  "BREXIT BARRIER", "TWINKLE TOEZZZ", "SKIDMARKED", "PYRAMID SCHEME 2.0",
  "FIRE FLY", "RAT FROST", "KISS OF MUD", "CHUNKY MONKEY",
  "BLOCK NESS MONSTER", "NETFLICKS & CHILL", "MOAT-ER FLOATING",
  "LUCIFER'S LUGGAGE", "POLE DANCER", "EVEREST", "RAIN MAN", "MUD MILE",
  "STAIRWAY TO HEAVEN", "SWINGS BOTH WAYS", "MUDDERHORN",
  "ELECTROSHOCK THERAPY",
];

const M_PER_MILE = 1609.344;
const kml = readFileSync(new URL("../data/course.kml", import.meta.url), "utf8");

function parsePlacemarks(xml) {
  const out = [];
  const re = /<Placemark[^>]*>([\s\S]*?)<\/Placemark>/g;
  let m;
  while ((m = re.exec(xml))) {
    const blk = m[1];
    const name = ((blk.match(/<name>([\s\S]*?)<\/name>/) || [])[1] || "").trim();
    const isLine = /<LineString>/.test(blk);
    const raw = ((blk.match(/<coordinates>([\s\S]*?)<\/coordinates>/) || [])[1] || "").trim();
    const coords = raw
      .split(/\s+/)
      .filter(Boolean)
      .map((t) => t.split(",").map(Number).slice(0, 2)); // [lon, lat]
    out.push({ name, isLine, coords });
  }
  return out;
}

function haversine(a, b) {
  const R = 6371000;
  const toR = (x) => (x * Math.PI) / 180;
  const dLat = toR(b[1] - a[1]);
  const dLon = toR(b[0] - a[0]);
  const h =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(toR(a[1])) * Math.cos(toR(b[1])) * Math.sin(dLon / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(h));
}

const placemarks = parsePlacemarks(kml);
const loop = placemarks.find((p) => p.isLine && /loop/i.test(p.name));
if (!loop) throw new Error("course loop LineString not found in KML");

// Cumulative distance along the loop.
const cum = [0];
for (let i = 1; i < loop.coords.length; i++) {
  cum[i] = cum[i - 1] + haversine(loop.coords[i - 1], loop.coords[i]);
}
const totalMiles = cum[cum.length - 1] / M_PER_MILE;

// Course as lat/lng points, each carrying its cumulative mile.
const course = loop.coords.map(([lon, lat], i) => ({
  lat: +lat.toFixed(6),
  lng: +lon.toFixed(6),
  mile: +(cum[i] / M_PER_MILE).toFixed(4),
}));

// Obstacles: keep their real KML coordinates, plus the mile of the
// nearest point on the loop (used for ordering / "next obstacle").
const obstacles = [];
for (const p of placemarks) {
  const m = p.name.match(/^\s*(\d+)\./);
  if (!m || p.isLine || p.coords.length !== 1) continue;
  const n = parseInt(m[1], 10);
  if (n < 1 || n > 20) continue;
  let best = 0, bestD = Infinity;
  for (let i = 0; i < loop.coords.length; i++) {
    const d = haversine(p.coords[0], loop.coords[i]);
    if (d < bestD) { bestD = d; best = i; }
  }
  obstacles.push({
    n,
    name: OBSTACLE_NAMES[n - 1],
    lat: +p.coords[0][1].toFixed(6),
    lng: +p.coords[0][0].toFixed(6),
    mile: +(cum[best] / M_PER_MILE).toFixed(3),
  });
}
obstacles.sort((a, b) => a.mile - b.mile);

const file = `// GENERATED by scripts/build-course.mjs from data/course.kml.
// Do not hand-edit COURSE/OBSTACLES — re-run the script instead.
// TIMING_MATS is safe to edit, but a re-run will reset it to [].

// Full lap length in miles.
export const LAP_MILES = ${totalMiles.toFixed(3)};

// One lap as { lat, lng } points, each with its cumulative mile.
export const COURSE = ${JSON.stringify(course)};

// Obstacles at their real coordinates; mile is the nearest loop point.
export const OBSTACLES = ${JSON.stringify(obstacles, null, 2)};

// Timing mats — add { name, lat, lng, mile } entries once known.
export const TIMING_MATS = [];
`;

writeFileSync(new URL("../assets/course-data.js", import.meta.url), file);
console.log(
  `course: ${totalMiles.toFixed(2)} mi, ${course.length} points, ${obstacles.length} obstacles`,
);
